title: Border
theme: minima
plugins: [jekyll-youtube]
author: this is messy here
email: poolsar.42@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Проект по борьбе с насилием

# social links
twitter_username: poolsarman # DO NOT include the @ character, or else the build will fail!
github_username:  poolsar42 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
